#!/usr/bin/env ruby

require_relative './lib/person'
require_relative './lib/nameable'
require_relative './lib/decorator'
require_relative './lib/capitalize'
require_relative './lib/trimmer'
require_relative './lib/student'
require_relative './lib/teacher'
require_relative './lib/classroom'
require_relative './lib/book'
require_relative './lib/rental'
require 'date'

class App
  def initialize
    @input = nil
    @students = []
    @teachers = []
    @books = []
    @options = ['List all books','List all people','Create a person','Create a book','Create a rental','List all rentals for a given person id','Exit']  
  end

  def run
    loop do
      options
      get_input
      validate(7)
      action_dispatch
    end
  end
  
  def options
    puts 'Ruby-School Library App'
    puts 'Please choose an option by entering a number:'
    @options.each_with_index { |option, ind| puts "#{ind + 1} #{option}" }
  end

  def get_input
    @input = gets.chomp
  end

  def validate(limit)
    unless ('1'..limit.to_s).to_a.include?(@input)
      loop do
        puts "Invalid entry. Please type a number between 1..#{limit}"
        @input = gets.chomp
        break if ('1'..limit.to_s).to_a.include?(@input)
      end
    end
  end

  def permission?
    true if @input == 'Y' || @input == 'y'
  end

  def action_dispatch
    case @input
    when 1.to_s
      books
    when 2.to_s
      people
    when 3.to_s
      person
    when 4.to_s
      book
    when 5.to_s
      rental
    when 7.to_s
      puts 'Programme ending...'
      exit(false)
    else
      puts "Error in action dispatch"
    end
  end

  def age
    puts 'Age:'
    get_input
    validate(120)
    @input
  end

  def name
    puts 'Name:'
    get_input
  end

  def student
    age_input = age
    name_input = name
    
    puts 'Has parent permission? [Y/N]:'
    get_input

    permission? ? @students << Student.new(age_input, name_input, permission?) : @students << Student.new(age_input, name_input)
    puts 'Student created successfully'
  end

  def teacher
    age_input = age
    name_input = name

    puts 'Specialization:'
    @teachers << Teacher.new(age_input, name_input, false, get_input)
    puts 'Teacher created successfully'
  end

  def person
    puts 'Do you want to create student (1) or teacher (2)? Type (1) or (2):'
    get_input
    validate(2)
    @input == '1' ? student : teacher
  end

  def book
    puts 'Title:'
    title = get_input

    puts 'Author:'
    author = get_input

    @books << Book.new(title, author)
    puts 'Book created successfully'
  end

  def books
    @books.each { |book| puts "Title: #{book.title} Author: #{book.author}" }
  end

  def people
    @students.each { |student| puts "[Students] Name: #{student.name} ID: #{student.id} Age: #{student.age}" }
    @teachers.each { |teacher| puts "[Teachers] Name: #{teacher.name} ID: #{teacher.id} Age: #{teacher.age}" }
  end

  def rental
    
  end
end

def main
  app = App.new
  app.run
end

main