#!/usr/bin/env ruby

require_relative './lib/person'
require_relative './lib/nameable'
require_relative './lib/decorator'
require_relative './lib/capitalize'
require_relative './lib/trimmer'
require_relative './lib/student'
require_relative './lib/classroom'
require_relative './lib/book'
require_relative './lib/rental'
require 'date'

class App
  puts 'Ruby-School Library App'
  puts 'Please choose an option by entering a number:'
end

def main
  App.new
end

main
