#!/usr/bin/env ruby

require_relative './lib/person'
require_relative './lib/nameable'
require_relative './lib/decorator'
require_relative './lib/capitalize'
require_relative './lib/trimmer'
require_relative './lib/student'
require_relative './lib/classroom'
require_relative './lib/book'
require_relative './lib/rental'
require 'date'

class App
  attr_reader :options, :user_select

  def initialize
    @input = nil
    @options = ['List all books','List all people','Create a person','Create a book','Create a rental','List all rentals for a given person id','Exit']  
  end
  
  def list
    puts 'Ruby-School Library App'
    puts 'Please choose an option by entering a number:'
    @options.each_with_index { |option, ind| puts "#{ind + 1} #{option}" }
  end

  def get_input
    @input = gets.chomp
    unless @input.match?(/[1-7]/)
      validate
    end
  end

  def validate
      loop do
        puts "Invalid entry. Please type a number between 1..7"
        @input = gets.chomp
        break if @input.match?(/[1-7]/)
      end
  end
end

def main
  app = App.new
  app.list
  app.get_input
end

main